# Configuratio for automatic builds and tests at travis-ci.com
language: python
python:
    - 3.5
install:
    - pip install -r requirements/dev.txt
    - pip install coveralls
script:
    - py.test -v --cov=oneiNote
after_success:
    - coveralls
