"""empty message

Revision ID: b0855cbee4df
Revises: 78d48ff15544
Create Date: 2016-09-06 10:37:56.254308

"""

# revision identifiers, used by Alembic.
revision = 'b0855cbee4df'
down_revision = '78d48ff15544'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_entries')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('google_cal_id', sa.INTEGER(), nullable=False),
    sa.Column('google_cal_entry_link', sa.VARCHAR(length=200), nullable=False),
    sa.Column('note_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_cal_entry_link')
    )
    ### end Alembic commands ###
